<?php
if ($this->params['countData'] > 0) :
    $operationBlock = '<ul class="unstyled">' . PHP_EOL;
    foreach ($this->operationSet as $operationAlias) {
        $operationBlock .= '<li><a title="'
            . $this->title[$operationAlias] . '" href="'
            . $this->baseUrl() /*. 'model/'*/ . $this->params['model']  . '/' . Mms_Manager::C_FORM . '/' . Mms_Control_Form::TYPE_UPDATE
            . '/id/%1$s" >' . $this->title[$operationAlias] . '</a></li>' . PHP_EOL;
    }
    $operationBlock .= '</ul>' . PHP_EOL;
?>
<table class="table table-striped table-bordered table-dash">
<thead>
    <tr>
        <th width=25><input type="checkbox" name="key[]" value="all"  id="toggleAll"/></th>
        <?php
        foreach ($this->aliasSet as $alias) {
            echo '<th>' . $this->title[$alias] . '</th>';
        }
        if ($operationBlock != '') {
            echo '<th>' . _t('Operation') . '</th>';
        }
        ?>

    </tr>
</thead>
<tbody id="checkboxes">
    <?php
    $i = 0;
    foreach ($this->data as $rowKey => $row) :
        $i++;
    ?>
        <tr class="toggleRow" data-line-number="<?= $i ?>">
        <td><input id="checkbox<?= $i ?>" type="checkbox" name="key[<?= $rowKey ?>]" value="<?= $rowKey ?>"></td>
<?php
foreach ($this->aliasSet as $alias) {
    $data = $row[$alias];
    if (empty($data) && $data != '0') {
        echo '<td></td>';
        continue;
    }
    echo '<td>';
    if (empty($this->metadata[Mms_Storage_Abstract::MD_FIELD][$alias]['tpl']) || $this->metadata[Mms_Storage_Abstract::MD_FIELD][$alias]['tpl'] == 'text') {
        echo $data;
    } else {
        try {
        echo $this->partial(
           'datagrid/' . $this->metadata[Mms_Storage_Abstract::MD_FIELD][$alias]['tpl'] . '.phtml',
            array(
                'alias' => $alias,
             	'data' => $row,
                'metaData' => $this->metadata[Mms_Storage_Abstract::MD_FIELD][$alias],
         ));
        }catch(Exception $ex) {
            echo $ex->getMessage();
        }
    }
    echo '</td>' . PHP_EOL;
}
if ($operationBlock != '') {
    echo '<td>' . vsprintf($operationBlock, array($row['id'])) . '</td>' . PHP_EOL;
}
?>
        </tr>
    <?php endforeach; ?>
</tbody>
</table>

<?php endif; ?>