<script language="javascript">
function toggleForm(){
	$("#add_form_fields").toggle();
	$("#add_form_btn").toggle();
}
</script>
<?php 
if (!empty($this->structure['scripts'])) {
    foreach ($this->structure['scripts'] as $alias) {
        echo '<script language="javascript" src="/js/' . $alias . '"></script>';                
    }
}
?>

<div id="add_form" class="actions">
	<button id="add_form_btn" class="btn primary" name="add" onClick="toggleForm()"><?= _t('Add new') ?></button>
</div>
<form action="" method="post">
<input type="hidden" name="operation" value="add" />
<!-- <fieldset id='add_form' class="collapsible">
	<legend id="add_form_legend" ><?= _t('Add new') ?></legend> -->
	<div id="add_form_fields" class="form" <?= ((count($this->data) > 0)? 'style="display: none;"' : '')?>>
	<? foreach ($this->structure['data'] as $key => $field) : ?>
	<?php if (($field['isEditable'] === true) || ($field['inCreation'] === true)) : ?>
	<div class="clearfix">
		<label for="element_<?= $key ?>"><?= ucfirst(Ik_Mongo_Document::getI18nValue($field['title']))?></label>
		<div class="input">
			<div class="input-prepend">
		<?php if ($field['field']['type'] === 'text') : ?>
			<span class="add-on <?= (($field['required'])?' required':'') ?>">&nbsp;</span>
			<input id="element_<?= $key ?>" name="<?= $field['alias'] ?>" class="small" type="text" placeholder="<?= $this->defaults[$field['alias']] ?>" />
		<?php elseif ($field['field']['type'] === 'select') :?>
			<span class="add-on <?= (($field['required'])?' required':'') ?>">&nbsp;</span>
			<select id="element_<?= $key ?>" name="<?= $field['alias'] ?>" class="small">
			<?php foreach ($field['field']['set'] as $elementKey => $element) : ?>
				<option value="<?= $elementKey ?>" <?= (($elementKey == $this->defaults[$field['alias']]) ? ' selected="selected"': '') ?> ><?= $element ?></option>
			<?php endforeach;?>
			</select> 
		<?php endif; ?>
			</div>
		</div>
		<?php if (isset($field['field']['desc'])) : ?>
		<p class="desc">
			<?= Ik_Mongo_Document::getI18nValue($field['field']['desc']) ?>
		</p>
		<?php endif; ?>
		<?php if (isset($field['field']['exampl'])) : ?>
		<span class="exampl">
			<?= $field['field']['exampl'] ?>
		</span>
		<?php endif; ?>
	</div>
	<?php endif; ?>
	<? endforeach; ?>
	<div class="actions">
		<button type="submit" class="btn primary" name="add"><?= _t('Add') ?></button>
		<button type="reset" class="btn" onClick="toggleForm()"><?= _t('Cancel') ?></button>
	</div>
	</div>
	 <!-- 
	</fieldset>
	 -->
</form>

