<form action="" method="post">
   <input type="hidden" name="operation" value="add" />
	<div id="add_form_fields" class="form" <?= (($this->params['countData'] > 0)? 'style="display: none;"' : '')?>>
    	<? foreach ($this->formAlias as $alias) : ?>
    	<div class="clearfix">
    		<label for="element_<?= $alias ?>"><?= ucfirst(($this->title[$alias]))?></label>
    		<div class="input">
    			<div class="input-prepend">
                <?= $this->partial(
                       'block/control/field/' . $this->fieldMetadata[$alias]['tpl'] . '.phtml',
                        array(
                            'inputId' => 'value1_' . $alias,
                         	'inputName' => 'form[' . $alias . ']',
                            'inputPlaceholder' => isset($this->defaults[$alias])?$this->defaults[$alias]:'',
                            'inputValue' => '',
                            'selectSet' => $this->selectSet,
                            'alias' => $alias,
                        )
                    );
                ?>
    			</div>
    		</div>
    	</div>
    	<? endforeach; ?>
    	<div class="actions">
    		<button type="submit" class="btn primary" name="add"><?= _t('Add') ?></button>
    		<button type="reset" class="btn" onClick="toggleForm()"><?= _t('Cancel') ?></button>
    	</div>
	</div>
</form>