<?php
if (!empty($this->scripts)) {
    foreach ($this->scripts as $script) {
        echo '<script language="javascript" src="/js/' . $script . '"></script>';
    }
}
if (empty($this->data)) {
    return;
}
$data = current($this->data);
?>
<div class="tabs-container">
    <ul id="tab" class="nav nav-tabs nav-stacked">
    <?php foreach (array_keys($this->groupSet) as $group) : ?>
        <li<?= ($group == $this->activeGroup) ? ' class="active"' : '' ?>>
            <a class="<?= $group ?>-data" data-toggle="tab" href="#<?= $group ?>"><?= ucfirst($this->title[$group]) ?></a>
        </li>
    <?php endforeach; ?>
    </ul>
</div>
<div class="tab-content tabs-content">
    <?php foreach ($this->groupSet as $group => $aliasSet) :?>
    <div id="<?= $group ?>" class="tab-pane<?= ($group == $this->activeGroup) ? ' active' : '' ?>">
    <?php if ($group == $this->activeGroup) :?>
        <div class="inline">
         <form class="form-horizontal">
	        <fieldset class="view">
	          <legend><?= ucfirst($this->title[$group]) ?><a href="#<?= $group ?>" class="btn btn-mini edit"><?= ucfirst(_t('edit')) ?></a></legend>
	          <?php foreach ($aliasSet as $key => $alias) :?>
             <div class="control-group">
                <label class="control-label" for="<?= $alias ?>"><?= ucfirst($this->title[$alias]) ?></label>
                <div id="<?= $alias ?>" class="controls">
                <?= $this->partial(
                    'block/control/field/view/' . $this->fieldMetadata[$alias]['tpl'] . '.phtml',
                    array(
                     	'field' => $data[$alias],
                        'listSet' => isset($this->selectSet[$alias]) ? $this->selectSet[$alias] : array(),
                        'fieldAlias' => $alias,
                )); ?>
                </div>
	          </div>
	          <?php endforeach; ?>
          </fieldset>
          <fieldset class="editing" style="display:none;">
	          <legend><?= ucfirst(_t('edite')) ?> <a href="#" class="btn btn-mini btn-primary apply"><?= ucfirst(_t('Save changes')) ?></a></legend>
             <?php foreach ($aliasSet as $key => $alias) :?>
	          <div class="control-group">
	            <label class="control-label" for="edit-<?= $alias ?>"><?= $this->title[$alias] ?></label>
	            <div class="controls" id="<?= $alias ?>Group">
	            	<?= $this->partial(
                    'block/control/field/' . $this->fieldMetadata[$alias]['tpl'] . '.phtml',
                    array(
                     	'field' => $data[$alias],
                        'id' => 'edit-' . $alias,
                        'name' => 'form[' . $alias . ']',
                        'placeholder' => $this->title[$alias],
                        'listSet' => isset($this->selectSet[$alias]) ? $this->selectSet[$alias] : array(),
                        'alias' => $alias,
                )); ?>
	            </div>
	          </div>
	          <?php endforeach; ?>
	          </fieldset>
        </form>
        </div>
        <?php endif; ?>
    </div>
    <?php endforeach; ?>
</div>