<?php
if (empty($this->data)) {
    return;
}
$data = current($this->data);
?>
<form action="" method="post" class="form-horizontal" id="updateForm">
    <input type="hidden" name="operation" value="<?= Mms_Storage_Abstract::OPERATION_UPDATE ?>" />
    <?php foreach ($this->aliasSet as $alias) : ?>
    <div class="control-group">
        <label for="element_<?= $alias ?>" class="control-label"><?= ucfirst(($this->title[$alias]))?></label>
        <div class="controls">
            <?= $this->partial(
            'field/' . $this->fieldMetadata[$alias]['tpl'] . '.phtml',
            array(
                'id' => 'value1_' . $alias,
                'name' => 'update[' . $alias . ']',
                'placeholder' => isset($this->fieldMetadata[$alias]['default'])
                    ? $this->fieldMetadata[$alias]['default']
                    : '',
                'field' => isset($data[$alias]) ? $data[$alias] : '',
                'valueSet' => (isset($this->valueSet[$alias]) ? $this->valueSet[$alias] : array()),
                'alias' => $alias,
            )
        );
            ?>
        </div>
    </div>
    <?php endforeach; ?>
    <div class="actions pagination-centered">
        <button type="reset" class="btn btn-danger"><?= _t('Cancel') ?></button>
        <button type="submit" class="btn btn-primary"><?= _t('Update') ?></button>
    </div>
</form>