<h4><?= _t('Filter') ?></h4>
<form class="form-inline" id="filterForm" method="post">
    <?php foreach ($this->filterParams['alias'] as $fieldAlias) : ?>
    <div class="row">
        <span class="span1"></span>
        <span class="span2"><?= $this->titleSet[$fieldAlias] ?></span>
        <span class="span2">
            <select class="input-small" id="query<?= $fieldAlias ?>" name="filter[<?= $fieldAlias ?>][0][not]" data-original-title="<?= _t('Excluded from the data') ?>">
                <option <?= ((!isset($this->postData[$fieldAlias]) || ($this->postData[$fieldAlias][0]['not'] == '0')) ? 'selected="selected"' : '' ) ?> value="0">Equal</option>
                <option <?= ((isset($this->postData[$fieldAlias]) && ($this->postData[$fieldAlias][0]['not'] == '1')) ? 'selected="selected"' : '' ) ?> value="1">Not equal</option>
            </select>
        </span>
        <span class="span3">
            <input
                id="inputField<?= $fieldAlias ?>"
                class="input-medium filterField"
                type="text"
                name="filter[<?= $fieldAlias ?>][0][val]"
                data-alias="<?= $fieldAlias ?>"
                value="<?= ((isset($this->postData[$fieldAlias]) && isset($this->postData[$fieldAlias][0]['val'])) ? $this->postData[$fieldAlias][0]['val'] : '' ) ?>"
            />
        </span>
    </div>
    <?php endforeach; ?>
    <div class="actions pagination-centered">
        <button id="filter_clear" type="reset" class="btn btn-danger"><?= _t('Cancel') ?></button>
        <button id="filter_submit" class="btn btn-primary"  disabled="disabled"><?= _t('Filter') ?></button>
    </div>
</form>
<script type="text/javascript" src="http://code.jquery.com/jquery-latest.min.js"></script>
<script type="text/javascript">
    var control = {
        sendForm: function(fieldsTag, formTag) {
            $(fieldsTag).each(function() {
                var field = $(this),
                    alias = field.attr('data-alias'),
                    value = field.val();
                if (value.length == 0) {
                    $('#query'+alias).attr('disabled', true);
                    field.attr('disabled', true);
                }
            });
            $(formTag).submit();
        },
        clearFilter: function() {
            var reload = false;
            $('.filterField').each(function() {
                var field = $(this),
                    value = field.val();
                if (value.length > 0) {
                    field.val('');
                    reload = true;
                }
            });
            if (reload) control.sendForm('.filterField', '#filterForm');
        }
    };
    $(function(){
        $('.filterField').on('keyup', function(){
            var button = $('#filter_submit');
            if (button.attr('disabled') == undefined) return;
            button.attr('disabled', false);
        });
        $('#filter_submit').on('click', function() {
            control.sendForm('.filterField', '#filterForm');
        });
        $('#filter_clear').on('click', function() {
            control.clearFilter();
        });
    });
</script>